In [27]:
import numpy as np

In [28]:
arr1=np.array([1,2,3,4,5,8.9])
arr1

array([1. , 2. , 3. , 4. , 5. , 8.9])

In [29]:
arr1=np.array([[1,2,3],[6,7,8]])
arr1


array([[1, 2, 3],
       [6, 7, 8]])

In [30]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
arr3=np.ones((2,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr3=np.identity(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
arr5=np.arange(9)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr5=np.arange(9,19)
arr5

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [10]:
arr5=np.arange(9,19,3)
arr5

array([ 9, 12, 15, 18])

In [11]:
arr6=arr5.copy()
arr6

array([ 9, 12, 15, 18])

In [12]:
arr5.ndim

1

In [13]:
arr5.shape

(4,)

In [14]:
arr1.size

6

In [15]:
arr1.dtype

dtype('int64')

In [16]:
lista=range(100)
arr1=np.arange(100)

In [17]:
import sys

In [18]:
print(sys.getsizeof(87)*len(lista))

2800


In [19]:
print(arr1.itemsize*arr1.size)

800


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
import numpy as np

arr = np.array({1, 2, 3, 4, 5})

print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


**0-D Arrays**

In [22]:
arr = np.array(42)

print(arr)

42


**1-D Arrays**

In [23]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**2-D Arrays**

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) #2D array are often used to represent matrix or 2nd order tensors.

[[1 2 3]
 [4 5 6]]


**3-D arrays**

In [25]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Checking No of Dimensions**

In [26]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Access Array Elements**

In [34]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [38]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [43]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('here we will access 2nd element on 1st row: ', arr[0, 1])

here we will access 2nd element on 1st row:  2


In [44]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6
