In [102]:
import numpy as np

In [103]:
arr1=np.array([1,2,3,4,5,8.9])
arr1

array([1. , 2. , 3. , 4. , 5. , 8.9])

In [104]:
arr1=np.array([[1,2,3],[6,7,8]])
arr1


array([[1, 2, 3],
       [6, 7, 8]])

In [105]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [106]:
arr3=np.ones((2,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [107]:
arr3=np.identity(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
arr5=np.arange(9)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
arr5=np.arange(9,19)
arr5

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [110]:
arr5=np.arange(9,19,3)
arr5

array([ 9, 12, 15, 18])

In [111]:
arr6=arr5.copy()
arr6

array([ 9, 12, 15, 18])

In [112]:
arr5.ndim

1

In [113]:
arr5.shape

(4,)

In [114]:
arr1.size

6

In [115]:
arr1.dtype

dtype('int64')

In [116]:
lista=range(100)
arr1=np.arange(100)

In [117]:
import sys

In [118]:
print(sys.getsizeof(87)*len(lista))

2800


In [119]:
print(arr1.itemsize*arr1.size)

800


In [120]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [121]:
import numpy as np

arr = np.array({1, 2, 3, 4, 5})

print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


**0-D Arrays**

In [122]:
arr = np.array(42)

print(arr)

42


**1-D Arrays**

In [123]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**2-D Arrays**

In [124]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) #2D array are often used to represent matrix or 2nd order tensors.

[[1 2 3]
 [4 5 6]]


**3-D arrays**

In [125]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Checking No of Dimensions**

In [126]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Access Array Elements**

In [127]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [128]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [129]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('here we will access 2nd element on 1st row: ', arr[0, 1])

here we will access 2nd element on 1st row:  2


In [130]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [131]:
# data type
a=np.array([1,2,3,0],dtype=bool)
# dtype float
b=np.array([1,2,3],dtype=float)
print(a)
print(b)

[ True  True  True False]
[1. 2. 3.]


In [132]:
# with reshape
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [134]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

**Array Attributes**

In [135]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [136]:
a3.ndim

3

In [137]:
a2.shape

(3, 4)

In [138]:
a2.itemsize

8

In [139]:
a1.itemsize

8

In [140]:
a3.itemsize

8

**Changing Datatype**

In [141]:
# astype
a3.dtype

dtype('int64')

In [142]:
# changing form 64 to 32
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [143]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
# arithmetic
a2 ** 2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [145]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [146]:
a1<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

**Array Functions**

In [147]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [148]:
np.max(a2)

np.int64(23)

In [149]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [150]:
np.min(a3)

np.int64(0)

In [151]:
np.sum(a3)

np.int64(28)

In [152]:
np.prod(a2)

np.int64(647647525324800)

In [153]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
# 0 -> col and 1 -> row
np.max(a1,axis=0)

array([ 8,  9, 10, 11])

In [155]:
np.mean(a3)

np.float64(3.5)

In [156]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [157]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[11.,  7., 61.],
       [66., 16., 78.]])

In [158]:
np.ceil(np.random.random((2,3))*100)

array([[89., 27., 96.],
       [54., 95., 21.]])

In [159]:
np.floor(np.random.random((2,3))*100)

array([[73., 52., 85.],
       [99.,  2., 89.]])

**Indexing and Slicing**

In [160]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
a2[1,1]

np.int64(5)

In [162]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [163]:
a3

2

In [164]:
a3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [165]:
a3.ndim

3

In [166]:
a3[0,1,0]

np.int64(3)

In [167]:
a3[1,1,1]

np.int64(8)

In [170]:
a4= np.array([[[[1,2],[3,4]],[[5,6],[7,8]],[[5,6],[7,8]]]])
print(a4)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]

  [[5 6]
   [7 8]]]]


In [171]:
a4.ndim

4

In [178]:
# Corrected code
a4[[0]]

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[5, 6],
         [7, 8]]]])

In [182]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [184]:
arr1[42:89]

array([42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
       76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])

In [185]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
a2[2,:]

array([ 8,  9, 10, 11])

In [187]:
a2[:,3]

array([ 3,  7, 11])

In [188]:
a2[1:,]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Iterating**

In [189]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
a1
for i in a1:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [193]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [194]:
for i in np.nditer(a3):
  print(i) #ya phla 2d ko 1d ma convert jara gha , pit itratuon kar agha

1
2
3
4
5
6
7
8


In [195]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [196]:
a3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [197]:
a4


array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[5, 6],
         [7, 8]]]])

In [198]:
a4.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

**Stacking**

In [204]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [205]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [206]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [207]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [211]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [212]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division

In [219]:
a5 = np.arange(42,82).reshape(,8)
a5

SyntaxError: invalid syntax (ipython-input-572566536.py, line 1)

In [214]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division